project_name: frodobot-gnm
run_name: frodobot-gnm
SACSoN: False
keep_learning: True

repo_id: frodobots_dataset
root: /media/noriaki/Noriaki_Data
episode-index: 0

late_fusion: False

# training setup
use_wandb: True # set to false if you don't want to log to wandb
train: True
batch_size: 150
eval_batch_size: 100
epochs: 200
gpu_ids: [0]
num_workers: 4
lr: 1e-4
optimizer: adamw
clipping: False
max_norm: 1.
scheduler: "cosine"
warmup: True 
warmup_epochs: 4
cyclic_period: 10
plateau_patience: 3
plateau_factor: 0.5
seed: 0

# model params
model_type: il_dist_gnm
obs_encoding_size: 1024
goal_encoding_size: 1024
vision_encoder: nomad_vint
encoding_size: 256
obs_encoder: efficientnet-b0
attn_unet: False
cond_predict_scale: False
mha_num_attention_heads: 4
mha_num_attention_layers: 4
mha_ff_dim_factor: 4
down_dims: [64, 128, 256]

# diffusion model params
num_diffusion_iters: 10

# FrodoBot dataset ratio
ratio_f: 0.1
horizon_short: 20

# mask 
goal_mask_prob: 0.5

# normalization for the action space
normalize: True

# context
context_type: temporal
context_size: 5 # 5
#alpha: 1e-4
alpha: 0.5

# distance bounds for distance and action and distance predictions 
distance:
  min_dist_cat: 0
  max_dist_cat: 20
action:
  min_dist_cat: 3
  max_dist_cat: 20

# action output params
len_traj_pred: 8
learn_angle: True

# dataset specific parameters
image_size: [96, 96] # width, height

datasets:
  frodobot:
    train: 11434305
    test: 11434305
    negative_mining: True
    
datasets_sub:
  recon:
    data_folder: /media/noriaki/Noriaki_Data/gnm_dataset/recon
    train: /media/noriaki/Noriaki_Data/learning-language-navigation_SACSoN/data_splits/recon/train/ # path to train folder with traj_names.txt
    test: /media/noriaki/Noriaki_Data/learning-language-navigation_SACSoN/data_splits/recon/test/ # path to test folder with traj_names.txt
    end_slack: 3 # because many trajectories end in collisions
    goals_per_obs: 1 # how many goals are sampled per observation
    negative_mining: True # negative mining from the ViNG paper (Shah et al.)
  go_stanford:
    data_folder: /media/noriaki/Noriaki_Data/gnm_dataset/go_stanford_cropped # datasets/stanford_go_new
    train: /media/noriaki/Noriaki_Data/learning-language-navigation_SACSoN/data_splits/go_stanford/train/
    test: /media/noriaki/Noriaki_Data/learning-language-navigation_SACSoN/data_splits/go_stanford/test/
    end_slack: 0
    goals_per_obs: 2 # increase dataset size
    negative_mining: True
  cory_hall:
    data_folder: /media/noriaki/Noriaki_Data/gnm_dataset/cory_hall
    train: /media/noriaki/Noriaki_Data/learning-language-navigation_SACSoN/data_splits/cory_hall/train/
    test: /media/noriaki/Noriaki_Data/learning-language-navigation_SACSoN/data_splits/cory_hall/test/
    end_slack: 3 # because many trajectories end in collisions
    goals_per_obs: 1
    negative_mining: True
  tartan_drive:
    data_folder: /media/noriaki/Noriaki_Data/gnm_dataset/tartan_drive
    train: /media/noriaki/Noriaki_Data/learning-language-navigation_SACSoN/data_splits/tartan_drive/train/
    test: /media/noriaki/Noriaki_Data/learning-language-navigation_SACSoN/data_splits/tartan_drive/test/
    end_slack: 3 # because many trajectories end in collisions
    goals_per_obs: 1
    negative_mining: True
  sacson:
    data_folder: /media/noriaki/Noriaki_Data/gnm_dataset/sacson
    train: /media/noriaki/Noriaki_Data/learning-language-navigation_SACSoN/data_splits/sacson/train/
    test: /media/noriaki/Noriaki_Data/learning-language-navigation_SACSoN/data_splits/sacson/test/
    end_slack: 3 # because many trajectories end in collisions
    goals_per_obs: 1
    negative_mining: True

  seattle:
    data_folder: /media/noriaki/Noriaki_Data/gnm_dataset/seattle/
    train: /media/noriaki/Noriaki_Data/learning-language-navigation_SACSoN/data_splits/seattle/train/
    test: /media/noriaki/Noriaki_Data/learning-language-navigation_SACSoN/data_splits/seattle/test/
    end_slack: 0
    goals_per_obs: 1
    negative_mining: True
  scand:
    data_folder: /media/noriaki/Noriaki_Data/gnm_dataset/scand/
    train: /media/noriaki/Noriaki_Data/learning-language-navigation_SACSoN/data_splits/scand/train/
    test: /media/noriaki/Noriaki_Data/learning-language-navigation_SACSoN/data_splits/scand/test/
    end_slack: 0
    goals_per_obs: 1
    negative_mining: True
    
  # private datasets (uncomment if you have access)
  # seattle:
  #   data_folder: /home/<username>/nomad_dataset/seattle/
  #   train: /home/<username>/data_splits/seattle/train/
  #   test: /home/<username>/data_splits/seattle/test/
  #   end_slack: 0
  #   goals_per_obs: 1
  #   negative_mining: True
  # scand:
  #   data_folder: /home/<username>/nomad_dataset/scand/
  #   train: /home/<username>/data_splits/scand/train/
  #   test: /home/<username>/data_splits/scand/test/
  #   end_slack: 0
  #   goals_per_obs: 1
  #   negative_mining: True

# logging stuff
## =0 turns off
print_log_freq: 100 # in iterations
image_log_freq: 1000 #0 # in iterations

#print_log_freq: 10 # in iterations
#image_log_freq: 10 #0 # in iterations

num_images_log: 30 #0 
pairwise_test_freq: 0 # in epochs
eval_fraction: 0.05
#eval_fraction: 0.9
wandb_log_freq: 10 # in iterations
eval_freq: 1 # in epochs

#load_run: frodobot-gnm/frodobot-gnm_2025_01_06_18_44_02
